### ISSUE TITLE
Veriseti

### ISSUE THREAD

**Issue by UcanYusuf** [Erenhub/Logistic-Regression-without-any-library#1]
Merhaba, verisetini paylaşabilir misiniz? Çok denedim ancak sanırım farklı bir veri seti kullandığım için çalıştıramadım. En başta np.load ettiğiniz csv dosyalarını da bulamadım. Yardımcı olabilirseniz çok memnun olurum.

**Comment by erenarkangil** [comment]
https://archive.ics.uci.edu/ml/datasets/optical%2Brecognition%2Bof%2Bhandwritten%2Bdigits
